# Site settings
title: Manuel Correa
email: mcorrea.web@gmail.com
description: "Manuel Correa github"
baseurl: ""
url: "http://manuelcorrea.github.io"

# Build settings
markdown: kramdown
permalink: pretty
